export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
//FOR GET ALL OF REOCRODS
export const FETCH_STREAMS = 'FETCH_STREAMS';
//FOR CREATE RECORDS
export const CREATE_STREAM = 'CREATE_STREAM';
//GET A SINGLE RECORD
export const FETCH_STREAM = 'FETCH_STREAM';
//GET A SINGLE RECORD
export const DELETE_STREAM = 'DELETE_STREAM';
//GET A SINGLE RECORD
export const EDIT_STREAM = 'EDIT_STREAM';
